### PR TITLE
remove zenith angle from RRTMGP.jl

### PR DESCRIPTION
**Pull request by claresinger**
Remove zenith angle docs from RRTMGP.jl because this is done by Insolation.jl and not needed here.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Can we add a description of why this is being removed? (I'm fine with this, it's being done in Insolation.jl, correct?)

**Comment by claresinger** [comment]
Yes, these docs are documenting something that is done by Insolation.jl. This PR is not removing any src/ code.

**Comment by charleskawczynski** [comment]
Should we remove the `RRTMGP.SolarZenithAngle` module if this will be done by Insolation.jl in the end?

**Comment by charleskawczynski** [comment]
Nevermind, the docs are just broken

**Comment by skandalaCLIMA** [comment]
> Yes, these docs are documenting something that is done by Insolation.jl. This PR is not removing any src/ code.

Hi Clare,
We will be precribing the insolation boundary conditions for the shortwave problem directly from ClimateMachine.jl. 
The sk/addlookup branch does the removal, but we are working on the full gas optics shortwave tests, before that can be merged.
But, it is ok to remove as we will be moving to insolation.jl anyways.

**Pull request merged**
