### PR TITLE
Fix typo in compute_col_dry_kernel!

### PR DESCRIPTION
**Pull request by sriharshakandala**
Fix typo in compute_col_dry_kernel!

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by sriharshakandala** [comment]
bors try

**Review by szy21 — APPROVED** [review]
Thanks Sriharsha! Should we add a test for dry air (so that it can capture this bug, for example)?

**Comment by sriharshakandala** [comment]
> Thanks Sriharsha! Should we add a test for dry air (so that it can capture this bug, for example)?

Our gray radiation code does not use this function. For the `RRTMGP` tests, all of them provide `vmr_h2o`. I can however remove the if-else statement, if this is an acceptable alternative!

**Comment by sriharshakandala** [comment]
bors try

**Review by szy21 — APPROVED** [review]

**Comment by sriharshakandala** [comment]
bors try

**Pull request merged**
