### PR TITLE
Use latest setup-julia action

### PR DESCRIPTION
**Pull request by simonbyrne**

### CODE REVIEW

**Review by skandalaCLIMA — APPROVED** [review]

**Comment by simonbyrne** [comment]
bors try

**Comment by simonbyrne** [comment]
@jakebolewski any idea what might be causing the failure here?

**Comment by simonbyrne** [comment]
posted a question here: https://forum.buildkite.community/t/identify-signal-in-error-the-command-was-interrupted-by-a-signal/1405

**Comment by jakebolewski** [comment]
@skandalaCLIMA can you change this line to not use hyphens and just underscores?

https://github.com/CliMA/RRTMGP.jl/blob/03eaba0d4236202a5c2f1944fdaf19631f6f72d8/.buildkite/ci-pipeline.yml#L14

Ex: `slurm_mem_per_cpu'

On slurm it's running out of memory and using the default allocation

**Comment by szy21** [comment]
Should we close this?

**Comment by sriharshakandala** [comment]
> Should we close this?

Yes. These changes were incorporated in a differnt PR.

**Pull request closed without merging**
