### PR TITLE
Longwave Driver for LES data

### PR DESCRIPTION
**Pull request by sriharshakandala**
Created a driver for computing fluxes based on LES data provided in the NetCDF file "HadGEM2-A_amip.2004-2008.07_site23_AtmosLESDefault_2020-10-07T12.46.14.887.nc"

### CODE REVIEW

**Comment by szy21** [comment]
I know I said it is reasonable to treat different times as different columns. But if it's not too much work, could you please set ncol=1 and loop over the times, so that the output variables will have the dimension (ntime, nlay)? It will be more consistent because we may have multiple columns for each timestep one day, just not now. Sorry for the inconvenience!

**Comment by skandalaCLIMA** [comment]
> I know I said it is reasonable to treat different times as different columns. But if it's not too much work, could you please set ncol=1 and loop over the times, so that the output variables will have the dimension (ntime, nlay)? It will be more consistent because we may have multiple columns for each timestep one day, just not now. Sorry for the inconvenience!

Yes. The plan is to use a call, similar to this driver, at each timestep.

**Comment by szy21** [comment]
I guess we could close this? We probably need to rewrite the LES driver given the code change.

**Comment by sriharshakandala** [comment]
> I guess we could close this? We probably need to rewrite the LES driver given the code change.

Yes. I agree.

**Pull request closed without merging**
