### PR TITLE
Set random seed

### PR DESCRIPTION
**Pull request by szy21**

### CODE REVIEW

**Comment by szy21** [comment]
This is trying to address #837 in ClimaAtmos. @charleskawczynski @sriharshakandala Could you check if I am doing the right thing?

**Review by charleskawczynski — COMMENTED** [review]
Random seeds are a bit complicated, since this sets the global random seed. @ilopezgp, and @haakon-e can attest to this. I think what we want is to pass an (optional?) `rng` into the function that calls this and set it appropriately.

**Comment by szy21** [comment]
So in ClimaAtmos we set random seed [here](https://github.com/CliMA/ClimaAtmos.jl/blob/fb5be4dbfd99103def412231e06c8bce123216a3/examples/hybrid/driver.jl#L87). How would that affect e.g. random seed in RRTMGP?

**Comment by szy21** [comment]
I see, thanks! Just talked with @sriharshakandala. For now we will set cloud fraction to 1 in ClimaAtmos to avoid the random number issue (The cloud fraction is only meaningful when there is EDMF). And we will come back to this problem once we have added tests on all-sky radiation.

**Pull request closed without merging**
