### PR TITLE
Add compat for NCDatasets.

### PR DESCRIPTION
**Pull request by sriharshakandala**
## Purpose 
NCDatasets v0.13.0 seems to have introduced some behavioral changes, breaking some tests. Compat entry restricts the version of NDDatasets used till appropriate updates can be made to codebase.

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by sriharshakandala** [comment]
bors try

**Comment by sriharshakandala** [comment]
bors try

**Review by szy21 — APPROVED** [review]

**Pull request merged**
